import { CookiesProvider } from "next-client-cookies/server"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <CookiesProvider>
          {children}
        </CookiesProvider>
      </body>
    </html>
  )
}
